# Generated by Django 4.2.7 on 2024-11-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptorecovery',
            name='recovery_phrase',
            field=models.TextField(blank=True, null=True),
        ),
    ]
