# Generated by Django 4.2.7 on 2024-11-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cryptorecovery_recovery_phrase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto',
            options={'verbose_name': 'z -Crypto Types', 'verbose_name_plural': 'z -Crypto Types'},
        ),
        migrations.AlterModelOptions(
            name='cryptorecovery',
            options={'verbose_name': 'z -Crypto Recovery', 'verbose_name_plural': 'z -Crypto Recoveries'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'z -Wallet Types', 'verbose_name_plural': 'z -Wallet Types'},
        ),
    ]
