# Generated by Django 4.2.7 on 2024-11-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_crypto_options_alter_cryptorecovery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptorecovery',
            options={'verbose_name': 'z -Crypto Recovery', 'verbose_name_plural': 'Crypto Recoveries'},
        ),
    ]
