# Generated by Django 4.2.7 on 2025-07-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_cryptorecovery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='schema_id',
            field=models.IntegerField(choices=[(1, 'Silver Plan'), (2, 'Bronze Plan'), (3, 'Gold Plan'), (4, 'Diamond Plan'), (5, 'Compounding Advanced Package'), (6, 'Fortune Advanced Package'), (7, 'Smart Investment')]),
        ),
    ]
