# Generated by Django 4.2.7 on 2024-10-10 02:59

import cloudinary.models
import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('CASH_APP', 'Cash App'), ('PAYPAL', 'PayPal'), ('ZELLE', 'Zelle')], max_length=10, null=True)),
                ('custom_method_name', models.CharField(blank=True, help_text='Leave blank if using a predefined method', max_length=50, null=True)),
                ('name_tag', models.CharField(help_text='Cash App Tag or PayPal/Zelle identifier', max_length=100)),
                ('qr_code_image', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('bank_image', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': '5- Aza Detail',
                'verbose_name_plural': '5-Aza Details',
            },
        ),
        migrations.CreateModel(
            name='CONTACT_US',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'CONTACT US',
                'verbose_name_plural': 'CONTACT US',
            },
        ),
        migrations.CreateModel(
            name='CRYPWALLETS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.CharField(blank=True, max_length=500, null=True)),
                ('bitcoin_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('ethereum', models.CharField(blank=True, max_length=500, null=True)),
                ('ethereum_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('usdt_erc20', models.CharField(blank=True, max_length=500, null=True)),
                ('usdt_erc20_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('solana', models.CharField(blank=True, max_length=500, null=True)),
                ('solana_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('usdt_trc20', models.CharField(blank=True, max_length=500, null=True)),
                ('usdt_trc20_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('xrp', models.CharField(blank=True, max_length=500, null=True)),
                ('xrp_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('bnb', models.CharField(blank=True, max_length=500, null=True)),
                ('bnb_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('litecoin', models.CharField(blank=True, max_length=500, null=True)),
                ('litecoin_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('dogecoin', models.CharField(blank=True, max_length=500, null=True)),
                ('dogecoin_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('shiba_inu', models.CharField(blank=True, max_length=500, null=True)),
                ('shiba_inu_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('cardano', models.CharField(blank=True, max_length=500, null=True)),
                ('cardano_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': '4- WALLETS',
                'verbose_name_plural': '4- WALLETS',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('target_email', models.EmailField(max_length=254)),
                ('note', models.TextField(default='none')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '3-Transfer',
                'verbose_name_plural': '3- Transfers',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('LOAN_REQUEST', 'Loan Request'), ('DEPOSIT', 'Deposit'), ('CRYPTO_WITHDRAW', 'Crypto Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined')], max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('target', models.CharField(blank=True, max_length=200, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('transaction_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_crypto_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaction Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SUPPORT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.CharField(choices=[('Please Select Customer Service Department', 'Please Select Customer Service Department'), ('Request For Transaction Files', 'Request For Transaction Files'), ('Customer Services Department', 'Customer Services Department'), ('Account Department', 'Account Department'), ('Transfer Department', 'Transfer Department'), ('Card Services Department', 'Card Services Department'), ('Loan Department', 'Loan Department'), ('Bank Deposit Department', 'Bank Deposit Department')], max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SUPPORT',
                'verbose_name_plural': 'SUPPORTs',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('BITCOIN', 'Bitcoin'), ('ETHEREUM', 'Ethereum'), ('USDT_TRC20', 'USDT TRC20'), ('USDT_ERC20', 'USDT ERC20'), ('XRP', 'XRP'), ('GIFTCARD', 'Giftcard'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('proof_of_pay', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('giftcard_type', models.CharField(blank=True, choices=[('Select Giftcard', 'Select Giftcard'), ('APPLE', 'Apple'), ('GOOGLE', 'Google'), ('ITUNES', 'iTunes'), ('AMAZON', 'Amazon')], max_length=20, null=True)),
                ('giftcard_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.banktransfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1- Manage Deposit/Payment',
                'verbose_name_plural': '1- Manage Deposit/Payment',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(default='default_notification_image.png', max_length=255, verbose_name='notification_images/')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_facility', models.CharField(choices=[('Personal Home Loans', 'Personal Home Loans'), ('Joint Mortgage', 'Joint Mortgage'), ('Automobile Loans', 'Automobile Loans'), ('Salary loans', 'Salary loans'), ('Secured Overdraft', 'Secured Overdraft'), ('Contract Finance', 'Contract Finance'), ('Secured Term Loans', 'Secured Term Loans'), ('StartUp/Products Financing', 'StartUp/Products Financing'), ('Local Purchase Orders Finance', 'Local Purchase Orders Finance'), ('Operational Vehicles', 'Operational Vehicles'), ('Revenue Loans and Overdraft', 'Revenue Loans and Overdraft'), ('Retail TOD', 'Retail TOD'), ('Commercial Mortgage', 'Commercial Mortgage'), ('Office Equipment', 'Office Equipment'), ('Health Finance Product Guideline', 'Health Finance Product Guideline'), ('Health Finance', 'Health Finance')], default='', max_length=40)),
                ('payment_tenure', models.CharField(choices=[('6 Months', '6 Months'), ('12 Months', '12 Months'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years')], default='', max_length=40)),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWITHDRAW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('BITCOIN', 'Bitcoin'), ('ETHEREUM', 'Ethereum'), ('USDT_TRC20', 'USDT TRC20'), ('USDT_ERC20', 'USDT ERC20')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recipient_address', models.CharField(default='', max_length=512)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2- Crypto Withdrawal',
                'verbose_name_plural': '2- Crypto Withdrawals',
            },
        ),
    ]
