# Generated by Django 4.2.7 on 2024-11-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newevent',
            options={'verbose_name': 'z - NewEvent', 'verbose_name_plural': 'z - NewEvents'},
        ),
        migrations.AlterModelOptions(
            name='neweventapplication',
            options={'verbose_name': 'z -Event Application', 'verbose_name_plural': 'z -Event Applications'},
        ),
        migrations.AlterModelOptions(
            name='recentwinner',
            options={'verbose_name': 'z - WINNER', 'verbose_name_plural': 'z - WINNERs'},
        ),
        migrations.RemoveField(
            model_name='newevent',
            name='wallet_address',
        ),
    ]
